<?php
// config/app_data.php

// Posortowana statyczna lista nauczycieli używana w widoku
$teachers = [
    'Bancerz Aneta',
    'Biadun Paweł',
    'Bielińska Aneta',
    'Bijata Mateusz',
    'Boreczek Dariusz',
    'Boreczek Monika',
    'Borkowska Anna',
    'Borkowska Ilona',
    'Chaber Dawid',
    'Cichowlas Karol',
    'Czarnecka Katarzyna',
    'Drygiel Daniel',
    'Duszek Beata',
    'Gawłowicz Joanna',
    'Grzyb Marcin',
    'Ignatowicz Beata',
    'Izdebska Agnieszka',
    'Janaszek Janusz',
    'Janowski Rafał',
    'Jurek Małgorzata',
    'Juszczyńska Małgorzata',
    'Karwowska Małgorzata',
    'Karwowski Sławomir',
    'Kłoczko Robert',
    'Koboj Arkadiusz',
    'Kopeć Mateusz',
    'Korgul Agnieszka',
    'Kozakiewicz Danuta',
    'Kożuch Anna',
    'Lesiewicz Dorota',
    'Linde Iwona',
    'Majczyna Justyna',
    'Markowska Joanna',
    'Moskwiak Małgorzata',
    'Narejko Mariusz',
    'Opalińska Katarzyna',
    'Opaliński Dariusz',
    'Pakuła Iwona',
    'Peplak Tomasz',
    'Petrowa Jolanta',
    'Pietrzak Anna',
    'Pietrzak Mirosław',
    'Pilich Natalia',
    'Pulik Wioletta',
    'Rodak Edyta',
    'Rokicka Małgorzata',
    'Rokicki Artur',
    'Rzepecki Wojciech',
    'Rzymowska Agata',
    'Rzymowska Ewa',
    'Sadło Marcin',
    'Sawicka Dorota',
    'Sawicki Bartosz',
    'Siwiec Weronika',
    'Smyk Wojciech',
    'Sozoniuk Monika',
    'Syrzycka Barbara',
    'Świder Michał',
    'Świerk Małgorzata',
    'Świętochowska Magdalena',
    'Tchórzewska-Sidor Anna',
    'Tchórzewski Damian',
    'Tomaszewska-Peryt Wioletta',
    'Wawryniuk Renata',
    'Wiatr Jakub Grzegorz',
    'Wiącek Małgorzata',
    'Wiącek Zbigniew',
    'Wojciechowski Radosław',
    'Wójcik Anna',
    'Wójcik Justyna',
    'Zaniewicz Daniel',
    'Zarzycka-Dmitruk Katarzyna',
    'Zemło Paweł',
    'Zielonka Wojciech',
    'Żurawska-Bijata Monika',
    'Żurawski Michał'
];
sort($teachers, SORT_LOCALE_STRING); // Gwarancja sortowania alfabetu PL np. (Ś, Ż), bez narzutu w GUI per req


// Posortowana naturalnie statyczna lista sal lekcyjnych
$rooms = [
    '1',
    '1a',
    '1b',
    '2',
    '3',
    '4a',
    '4b',
    '5',
    '6',
    '7',
    '8',
    '9',
    '10',
    '11',
    '12',
    '13',
    '14',
    '15',
    '16',
    '17',
    '18',
    '19',
    '20',
    'B1',
    'B2',
    'B3',
    'B4',
    'B5',
    'B6',
    'bo1',
    'bo2',
    'bo3',
    'bo4',
    'cen',
    'int',
    'JO',
    'k1',
    'k2',
    'k3',
    'k4',
    'K5',
    'kate1',
    'kate2',
    'kate3',
    'kate4',
    'kuch.',
    'm1',
    'm2',
    'm3',
    'm4',
    'm5',
    'Sala',
    'wdż'
];
sort($rooms, SORT_NATURAL | SORT_FLAG_CASE);
